### ISSUE TITLE
Sparse domain support for categorical vars

### ISSUE THREAD

**Issue by alldefector** [HazyResearch/numbskull#37]
The sparse domain implementation in DW isn't particularly efficient, but it's used in many apps. Do we have a plan to support that soon (so we can test on a wider range of DD apps)? If no one has started working on it, I'd be happy to take the first stab.

**Comment by chrismre** [comment]
I must have lost track. What is inefficient about it? How inefficient is it?

We do use this feature everywhere...

**Comment by alldefector** [comment]
OK, that was probably an "over-exaggeration"... Algorithmically it's constant time, but the data structures (hash tables) are not compact as with VarInFactor and CompactFactor arrays:
https://github.com/HazyResearch/sampler/blob/master/src/factor.h#L339-L350
https://github.com/HazyResearch/sampler/blob/master/src/variable.h#L48-L50

Optimizing those data structures might improve the perf further, but I don't have numbers for how much saving that could potentially be.

**Comment by alldefector** [comment]
It's not straightforward to port these hash tables: on the one hand, py dict wouldn't fly: http://numba.pydata.org/numba-doc/latest/glossary.html#term-object-mode; on the other, it'll take some effort to figure out how to add a low-level hash table implementation (say C) to numba.

The variable value tables should be easy to linearialize -- we can just stick with "domain index" and do the translation from "domain value" on assignments and factor specs at loading time. We haven't done that with DW, so may want to do it there first...

The factor param tables (keyed on a tuple of variable values) are another level of sparsity. They seem tricky to deal with as long as we keep the current definition of "a factor" (namely one that can correspond to multiple weights keyed on the var values)...
