### ISSUE TITLE
python3?

### ISSUE THREAD

**Issue by alldefector** [HazyResearch/numbskull#39]
The code is using py3 syntax like `print(...)`. Any reason for using py2 instead of py3 (which is the future)? cc @xiaoling

**Comment by chrismre** [comment]
probably a wrongheaded advisor hates python3, but we can switch... are there any numba issues?

**Comment by alldefector** [comment]
None (of numba issues) that I know of.

**Comment by thodrek** [comment]
@bryan-he please correct if i am wrong. py2 was chosen for compatibility with snorkel. Prints are in py3 syntax due to numba

**Comment by alldefector** [comment]
@thodrek I actually had the same question (2 vs 3) about snorkel...

**Comment by ajratner** [comment]
@alldefector We've just been using python 2.7 because it seems to still be
the default installed version on many systems, seems safer to use from a
compatibility / distribution perspective

**Comment by bryan-he** [comment]
Numbskull is using python2 for Snorkel compatibility.

The prints are in python3 syntax by using
>> from __future__ import print_function

If you don't do this, numba generates warnings.

**Comment by alldefector** [comment]
Thanks, @bryan-he ! @xiaoling tested the py3 version on the memex1 load and the chunking load, and both resource usage and results were on par with py2.
