### ISSUE TITLE
Inconsistent parameter name with dimmwitted

### ISSUE THREAD

**Issue by xiaoling** [HazyResearch/numbskull#40]
First of all, great stuff here! If I understand correctly, numbskull is to replace dimmwitted, or at least serve as an alternative. If that's the case, it would be helpful to have the same parameter names to make deepdive applications compatible with both numbskull and dimmwitted. 

One thing I found inconvenient is that dimmwitted is using `--alpha (-a)` for the stepsize parameter whereas numbskull is using `-s`. This inconsistency makes me  write two configurations. Can someone unify the names?

Thanks!

**Comment by bryan-he** [comment]
I just pushed a commit to add `-a` and `--alpha` as options for the stepsize parameter.

Are there any other parameter names that are not consistent?

**Comment by xiaoling** [comment]
Thanks! I haven't used all the parameters but here is a list of parameters from `sampler-dw gibbs -h`. I don't think `-p` is in use (someone else should verify) but a quick scan shows that the regularization param is inconsistent (`-r` vs `-b`). 
```
   --learn_non_evidence  (accepted multiple times)
     sample non-evidence variables in learning

   --sample_evidence  (accepted multiple times)
     also sample evidence variables in inference

   -q,  --quiet  (accepted multiple times)
     quiet output

   --regularization <string>  (accepted multiple times)
     Regularization (l1 or l2)

   -b <double>,  --reg_param <double>  (accepted multiple times)
     l2 regularization parameter

   -d <double>,  --diminish <double>  (accepted multiple times)
     Decay of stepsize per epoch

   -p <double>,  --stepsize <double>  (accepted multiple times)
     Stepsize

   -a <double>,  --alpha <double>  (accepted multiple times)
     Stepsize

   -t <int>,  --n_threads <int>  (accepted multiple times)
     Number of threads to use. Use 0 for all available threads (default)

   -c <int>,  --n_datacopy <int>  (accepted multiple times)
     Number of factor graph copies. Use 0 for all available NUMA nodes
     (default)

   --burn_in <int>  (accepted multiple times)
     Burn-in period

   -i <int>,  --n_inference_epoch <int>  (accepted multiple times)
     (required)  Number of Samples for Inference

   -l <int>,  --n_learning_epoch <int>  (accepted multiple times)
     (required)  Number of Learning Epochs

   --domains <string>
     Categorical domains

   -o <string>,  --outputFile <string>
     Output Folder

   -w <string>,  --weights <string>
     weights file

   -f <string>,  --factors <string>
     factors file

   -v <string>,  --variables <string>
     variables file

   -m <string>,  --fg_meta <string>
     factor graph metadata file

   --,  --ignore_rest
     Ignores the rest of the labeled arguments following this flag
```

**Comment by bryan-he** [comment]
I just pushed another few commits that makes the NS command line more similar to the DW command line.

I think the following things are the only remaining differences.

1. DW uses `-b` for the regularization parameter and NS uses `-r`. Right now, NS uses `-b` for the number of burn-in sweeps, which is convenient. Would it make sense to change DW to use this, or would it break other things?
2. NS doesn't support `-p` for stepsize. If this is actually in use, I can add the option, but I would rather not add redundant options unless necessary.
3. `-c`, `--n_datacopy` not supported right now. NS isn't NUMA-aware yet.
4. `--outputFile` becomes `--output_dir`. This is actually specifying a directory for the inference and learning output files, so I think this naming convention makes slightly more sense.
5. `--`, `--ignore_rest` aren't supported by NS right now. Is this option commonly in use?

**Comment by xiaoling** [comment]
I can't speak for all but I don't think `-p` is currently in use in DW (https://github.com/HazyResearch/deepdive/issues/204) nor is `ignore_rest`. I'm aware of 3. I'm ccing @alldefector @netj for 1 and 4.

**Comment by xiaoling** [comment]
It seems this issue has been addressed. thanks @bryan-he
